### PR TITLE
Delete ruby-vanessa-rashad.rb

### PR DESCRIPTION
**Pull request by HeavyArms0511**

### CODE REVIEW

**Comment by HeavyArms0511** [comment]
Was trying to do something mixed it up.

**Review by SunkissedQueen — COMMENTED** [review]
This file looks like it belongs to another group. Are you sure that you want to delete their work?

**Comment by HeavyArms0511** [comment]
I will ask them and see on checkout

**Review by WalkerTexas-coder — COMMENTED** [review]
are you sure?

**Comment by HeavyArms0511** [comment]
Its an empty file

**Review by WalkerTexas-coder — APPROVED** [review]

**Pull request merged**
